### ISSUE TITLE
404 while accessing a route

### ISSUE THREAD

**Issue by Fanom2813** [kwameopareasiedu/vanjs-routing#1]
Hello , i am new to van js, i am having trouble access a specific route directly , for example:

if i access `website.com` then i go to `website.com/about` it works properly , but if try to navigate directly to `website.com/about` i get `404`

here is my code

```
import van from "vanjs-core";
import { Router} from "vanjs-routing";

import HomePage from "./pages/home";
import AboutPage from "./pages/about";
import PrivacyPolicyPage from "./pages/privacy";
import TermsPage from "./pages/terms";
import RefundPolicy from "./pages/refund-policy";

function App() {
  return Router({
    routes: [
      { path: "/", component: HomePage },
      { path: "/about", component: AboutPage },
      { path: "/privacy-policy", component: PrivacyPolicyPage },
      { path: "/terms-and-conditions", component: TermsPage },
      { path: "/refund-policy", component: RefundPolicy },
      { path: "*", component: HomePage },

    ]
  });
}

van.add(document.body, App());
```

i navigate with  : `a({ onclick:() => navigate('/'), class: "footer-logo" })`

thanks.

**Comment by kwameopareasiedu** [comment]
Hello @Fanom2813 Thanks for reporting this. I'd like to know how the site is being served when u enter the URL directly.

**Comment by Fanom2813** [comment]
i built the app with  `"build": "tsc && vite build",` and hosted the dist folder in apache hosting provider

**Comment by Fanom2813** [comment]
> From the description it seems like navigating to `website.com/about` directly is processed by a server which has not been configured to return the page on every route.
> 
> `vanjs-routing` is a client-side navigation library (which is why it works when u visit `website.com` first and navigate to /about). If the above is correct, you'll need to configure your server to return the frontend on every route path.

can you illustrate this please

**Comment by kwameopareasiedu** [comment]
To illustrate:
1. Open `website.com`
2. Navigate to `/about`
3. Refresh the page

U should get a 404 after refresh.

- When u build the files, Vite generates an index.html along with the bundled JS and a CSS file. When u place these at the root of the Apache hosting provider.

- When u request `website.com` (I.e. the index), the Apache server looks for a corresponding index file in the directory which is returned to the client.

- Now when u try to access `website/about` directly, I'm thinking the Apache provider is looking for a corresponding file and since u don't have an about.html file, it returns a 404.

---

The reason navigating to about when on the index page works is, it's done client side, so no request is sent to the Apache provider for a new page. Contrary to this, when u refresh the page or access `website.com/about` directly, the browser sends a new page request and hence a 404.

**Comment by kwameopareasiedu** [comment]
The solution would be to configure the Apache hosting provider to always return the index.html for all requested paths. When the app is loaded, `vanjs-routing` will now take over and route to correct component.

**Comment by Fanom2813** [comment]
> The solution would be to configure the Apache hosting provider to always return the index.html for all requested paths. When the app is loaded, `vanjs-routing` will now take over and route to correct component.

got it ! thanks
